### ISSUE TITLE
pip for dapr-client still in version 0.1, need to publish 0.2 and then 0.3

### ISSUE THREAD

**Issue by artursouza** [dapr/python-sdk#13]
## Expected Behavior

pip install dapr-client should install the latest version (0.2 now)

## Actual Behavior

installs the first version 0.1

## Steps to Reproduce the Problem

pip search dapr-client

or 

open https://pypi.org/project/dapr-client/

**Comment by amanbha** [comment]
0.1 is the latest version, python sdk hasn't been updated yet, to do a next release.
