### ISSUE TITLE
For invoke Service - How to return error over grpc. 

### ISSUE THREAD

**Issue by trondhindenes** [dapr/python-sdk#141]
## Ask your question here
As far as I can see, the `InvokeServiceResponse` object doesn't implement any obvious way of returning errors to the caller.

I'm trying to understand how I would go about indicating a non-success status to a service invocation call.

**Comment by youngbupark** [comment]
the current behavior will throw the grpc rpc exception if callee has an error. then you need to catch this exception. but we realize that this way is difficult to get the actual error code. So we're planning to change the error handling design in 1.0.0 Milestone 2.

Please see [this proposal](https://github.com/dapr/dapr/issues/2342) for more details

**Comment by msfussell** [comment]
@trondhindenes - Due this issue https://github.com/dapr/dapr/issues/2342 we are changing the way that this works and RC3 will come out with new documentation. Hence closing this issue and new ones will be opened.
