### ISSUE TITLE
Update branding to reflect RC instead of alpha

### ISSUE THREAD

**Issue by mukundansundar** [dapr/python-sdk#151]
## Describe the proposal
Since Dapr is in RC we should use RC branding in the package names. We should update the versions to say 1.0.0-rc-1 or similar.

This will be for the 1.0.0 release of Dapr alone and from then on the versions of the SDKs will diverge. This has been proposed and discussed for all SDKs.

With that in mind, and taking into account PEP versioning https://www.python.org/dev/peps/pep-0440/#pre-releases

we will release v1.0.0rc.2 for the dapr RC2 milestone, to get it in sync with the core release.

RELEASE NOTE: **UPDATE** versioning for Python SDK to 1.0 RC

**Comment by youngbupark** [comment]
I am supporting this decision to sync with the dapr core release.
