### ISSUE TITLE
Actor Implementation

### ISSUE THREAD

**Issue by thebillkidy** [dapr/python-sdk#16]
I currently do not see a way to implement actor methods, is this already supported in the Python SDK? 😊

**Comment by youngbupark** [comment]
No, Dapr core team does not have the official plan to support actor feature in Python SDK now.

But I have spent my own time to add actor feature to python-sdk as a personal project. Again, this is not in the official plan. If you're interested in this work, please look at [my initial PR](https://github.com/dapr/python-sdk/pull/18). There is an example for actor service invocation.

**Comment by thebillkidy** [comment]
Awesome, thanks a lot! This issue can be closed then
