### ISSUE TITLE
Allow for a more recent version of grpcio

### ISSUE THREAD

**Issue by alydersen** [dapr/python-sdk#160]
Hi guys, and thank you so much for your awesome work!

I'm having some issues installing the dapr-fast-api packages now, based on the requirement of the grpcio version being ==1.26.0. Is there any specific reason it needs to be that exact version, or could we change it to at least >=1.26.0? That version is one year old and the current version is .1.34.0.

https://github.com/dapr/python-sdk/blob/fa1116c640f7c30d6295ce1033475032a4a9c0d3/dev-requirements.txt#L7

BR,
Andreas

**Comment by youngbupark** [comment]
@alydersen Thanks for your interest. initially, we want to use the same version of gPRC library with dapr/dapr. but now we can use the the latest version of gRPC because dapr/dapr uses the 1.3x. 

If you have a time, can you please create the PR to contribute to Dapr ?

**Comment by alydersen** [comment]
More than happy to contribute @youngbupark! #161 closes this issue to the best of my knowledge.
