### ISSUE TITLE
Set the timeout for ActorProxy

### ISSUE THREAD

**Issue by alydersen** [dapr/python-sdk#162]
Hi everybody,

We have a few issues regarding errors and timeouts when talking to the actors that we are ironing out. The question is if it its possible to tweak the default timeout of 60 seconds on the ActorProxy or otherwise instantialize the class? I guessing there will be very few cases where 60 seconds is needed?

Thanks!
Andreas

RELEASE NOTE: **ADD** Add DAPR_HTTP_TIMEOUT_SECONDS configuration option.

**Comment by wcs1only** [comment]
We can indeed add a timeout value to the public interface.

**Comment by wcs1only** [comment]
So we're adding two ways to do this. You can set the environment variable DAPR_HTTP_TIMEOUT_SECONDS

or

```python
proxy = ActorProxyFactory(http_timeout_seconds=10).create('actor_type', 'actor_id')
```
