### ISSUE TITLE
why not organize the ext package into dapr

### ISSUE THREAD

**Issue by gaoxinge** [dapr/python-sdk#166]
## Ask your question here

Now whole project is divided into four packages:

- [dapr](https://github.com/dapr/python-sdk/tree/master/dapr)
- [dapr-ext-fastapi](https://github.com/dapr/python-sdk/tree/master/ext/dapr-ext-fastapi)
- [dapr-ext-grpc](https://github.com/dapr/python-sdk/tree/master/ext/dapr-ext-grpc)
- [flask_dapr](https://github.com/dapr/python-sdk/tree/master/ext/flask_dapr)

which may be intended for that 

- `dapr` itself is independent of others, and
- `dapr-ext-fastapi`, `dapr-ext-grpc` and `flask_dapr` are extensions for `dapr`.

However some evidences show these packages may be better to organize into one package:

- If one install package `dapr-ext-grpc`, he will find that `dapr-ext-grpc` is actually named as `dapr.ext.grpc` in local, which shares the same package name of `dapr`.
- If one dig more into the codes, he will find the package `dapr-ext-grpc` uses the private variables from `dapr`, like
https://github.com/dapr/python-sdk/blob/87e9d11d20f8cdc8ed73072e3087700233421b49/ext/dapr-ext-grpc/dapr/ext/grpc/_servicier.py#L17-L18

**So my question is that why whole project is divided into four packages?**

**Comment by artursouza** [comment]
Because users don't need to use all the extensions. New extensions can be created independently from the core project. Also, extensions can be deprecated independently from the core project. This is the same design for the other SDKs. See https://github.com/dapr/java-sdk and https://github.com/dapr/dotnet-sdk
