### ISSUE TITLE
etag mismatch returns a different error code by runtime

### ISSUE THREAD

**Issue by vinayada1** [dapr/python-sdk#167]
## Expected Behavior
dapr runtime changes the error code returned by the state apis for etag mismatch related errors and other errors. Check if the sdk needs a change. https://github.com/dapr/dapr/pull/2647

## Actual Behavior

Check if sdk needs a change to distinguish between etag mismatch and other state api issues

## Steps to Reproduce the Problem

Error code internal is returned when state api fails due to etag mismatch error

## Release Note

RELEASE NOTE: **ADDED** code in state store example showcasing etag handling.

**Comment by artursouza** [comment]
@vinayada1 I looked into this issue. Today, the Python SDK does not have an abstraction for the grpc exceptions. So, all the exceptions just pass through to the app. There is not much work to do here, apart from updating the example to demonstrate the etag mismatch scenario. See PR above.
