### ISSUE TITLE
Updates for next runtime RC

### ISSUE THREAD

**Issue by artursouza** [dapr/python-sdk#192]
Update the SDK for the following breaking changes:

1. Service invocation now handles queryparams as string and not Map of string->string. Get the latest proto and fix any code in the SDK that refers to that.

2. When content type is "application/octet-stream", CloudEvent's data will now be in `data_base64` and that should be exposed as `byte[]` to the application.

**Comment by wcs1only** [comment]
We discovered while working on this, we shouldn't actually need any changes to the python API for data_base64, however in the process, we discovered a runtime bug. Closing in favor of dapr/dapr#2794
