### ISSUE TITLE
Sample Dockerfile in examples/invoke-simple/ shouldn't have python CMD

### ISSUE THREAD

**Issue by ms-kashyap** [dapr/python-sdk#195]
## Expected Behavior

When following the README in examples/invoke-simple/, you're supposed to build a Docker image from the included Dockerfile. However, the last command in this Dockerfile is `CMD [ "python", "invoke-receiver.py" ]`. 

My understanding was that you don't need to specify this command at all because the yaml files in deploy/ already tell Kubernetes to run `invoke-receiver.py` and `invoke-caller.py`.

## Actual Behavior

The Dockerfile in examples/invoke-simple/ has the `CMD [ "python", "invoke-receiver.py" ]` command, which is unnecessary and may result in errors in Kubernetes. Please correct me if I'm wrong.

## Steps to Reproduce the Problem

N/A 

## Release Note

RELEASE NOTE: Fix invoke-simple Dockerfile

**Comment by wcs1only** [comment]
I just verified this, it works as is. You're right in that we don't need it, and I think it only exists for the sake of running the container locally outside of k8s.

If you are having trouble, can you confirm for me what your Kubernetes setup is like? What version/provider are you using?

**Comment by wcs1only** [comment]
This is issue is stale. Closing. If this is actively causing an issue for you, please open a new issue with details on what the issue is and how to reproduce it.
