### ISSUE TITLE
gevent compatibility

### ISSUE THREAD

**Issue by seewindcn** [dapr/python-sdk#202]
## Describe the proposal
Can dapr sdk work with gevent?  
this can make dapr support wide normal no async python package; 

http://www.gevent.org/
grpc already support gevent: https://github.com/grpc/grpc/issues/4629

**Comment by wcs1only** [comment]
So, as I understand it, gevent provides tools to add support to 3rd party libraries should you choose to use it. What is it that you would need to change in the python-sdk to enable this?

Also, this may have implications for the actor framework, as it expects to be single threaded async. Does gevent break this assumption?

I'd love to hear more about your use case.

**Comment by wcs1only** [comment]
Since we haven't had any movement on this issue in many months, I'm going to go ahead and close it as stale. If you would like to restart this conversation, please create an issue, or reach out on our community Discord:
https://aka.ms/dapr-discord
