### ISSUE TITLE
`tox -e doc` command failed

### ISSUE THREAD

**Issue by kaypee90** [dapr/python-sdk#205]
I have python 3.9 installed and I ran `tox -e doc` command for documentation and it threw this error `ERROR: InterpreterNotFound: python3.7`. Are there any prerequisites before running this command?

**Comment by wcs1only** [comment]
So, our requirements are for python >=3.7. Our tox.ini definitions are probably too restrictive.

If you just want to get yourself unblocked, you can install a python3.7 interpreter.
