### ISSUE TITLE
Non-asyncio actor implementation support?

### ISSUE THREAD

**Issue by Junnplus** [dapr/python-sdk#216]
## Describe the proposal

Current actor implementation uses asyncio, but seem asyncio is not mainstream in Python, whether actor will support the implementation of non-asyncio?

**Comment by wcs1only** [comment]
One of the primary requirements of actors is that they be single threaded to ensure memory consistency. That makes asyncio somewhat necessary to ensure that all operations are not blocking. Otherwise a single long running IO request could block all executions.
