### ISSUE TITLE
Implement State Isolation for Reentrant Actor Calls

### ISSUE THREAD

**Issue by halspang** [dapr/python-sdk#237]
## Describe the proposal
Without state isolation, a reentrant call can commit state changes from anywhere in the call stack. Instead of allowing this, we should stop actors from being able to modify the state of previous actors. 

The proposal here is to allow for state snapshots to be used instead of accessing the `StateManager` directly. This should be achievable with Python's `ContextVars`. When a reentrant request comes in (or potentially all requests), generate a GUID and set the `StateManager` to use that. All changes, resets, or commits, will then go to that contextual state. This will stop the state from spreading to different requests.

Essentially, just add a layer of abstraction above the `state_change_tracker` that uses a `ContextVar` to track which `state_change_tracker` we're in.

**Comment by berndverst** [comment]
I'll take a look!
