### ISSUE TITLE
Invoke method DemoActor (FastAPI) via curl

### ISSUE THREAD

**Issue by shlyopin** [dapr/python-sdk#243]
Hello!

I'm starting "demo_actor_service.py" (dapr run --app-id demo-actor --app-port 3000 -- uvicorn --port 3000 demo_actor_service:app)
and trying to invoke "PUT /actors/DemoActor/1/method/GetMyData" with actor_id = 1

log on the server:
`== APP == Activate DemoActor actor!`
`== APP == INFO:     127.0.0.1:35018 - "PUT /actors/DemoActor/1/method/GetMyData HTTP/1.1" 500 Internal Server Error`

log on curl:
`{"message":"actor instance is missing","errorCode":"ERR_ACTOR_INSTANCE_MISSING"}`

If I started the "demo_actor_client.py", the request works correctly until the server is restarted. The client activate instance of actor with actor_id, but "PUT /actors/DemoActor/1/method/GetMyData" don't create actors instance. 

Is this normal behavior or a bug?

**Comment by avvijeet** [comment]
Hey @shlyopin, this is a known bug flagged out by a fellow developer in Dapr Discord Python-sdk group.

**Comment by wcs1only** [comment]
Could you post your exact curl command? If you are trying to invoke an actor, you need to do so through the dapr API, and it looks like you are trying to invoke the python application directly?

**Comment by shlyopin** [comment]
> Could you post your exact curl command? If you are trying to invoke an actor, you need to do so through the dapr API, and it looks like you are trying to invoke the python application directly?

Yes, i trying to invoke the python application directly via the FastAPI. 
There is a public API that allows you to do this, but does not work.
I did not have any problems with calling through Dapr API

I ran demo_actor_service without demo_actor_client and trying to execute the request: curl -X 'PUT' 'http://localhost:3000/actors/DemoActor/1/method/GetMyData' -H 'accept: application/json'
Response result: {"message":"actor instance is missing","errorCode":"ERR_ACTOR_INSTANCE_MISSING"}

**Comment by shlyopin** [comment]
> Hey @shlyopin, this is a known bug flagged out by a fellow developer in Dapr Discord Python-sdk group.

Thank you, I subscribed to the channel!

**Comment by wcs1only** [comment]
So in order to do what you are trying to do, you need to be talking to a dapr sidecar. This is what handles actor activation and enforces the property that only one actor can be activated at once. Try this instead:

```
dapr run --app-id demo-actor --app-port 3000 -- uvicorn --port 3000 demo_actor_service:app                            
```

```
dapr run -- bash -c 'curl -vX "PUT" "http://localhost:$DAPR_HTTP_PORT/v1.0/actors/DemoActor/1/method/GetMyData" -H "accept: application/json"'
```

When I run this I get:
```
== APP ==   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
== APP ==                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying ::1...
== APP == * TCP_NODELAY set
== APP == * Connection failed
== APP == * connect to ::1 port 59748 failed: Connection refused
== APP == *   Trying 127.0.0.1...
== APP == * TCP_NODELAY set
== APP == * Connected to localhost (127.0.0.1) port 59748 (#0)
== APP == > PUT /v1.0/actors/DemoActor/1/method/GetMyData HTTP/1.1
== APP == > Host: localhost:59748
== APP == > User-Agent: curl/7.64.1
== APP == > accept: application/json
== APP == > 
== APP == < HTTP/1.1 200 OK
== APP == < Server: uvicorn
== APP == < Date: Thu, 05 Aug 2021 15:34:01 GMT
== APP == < Content-Type: application/json; utf-8
== APP == < Content-Length: 4
== APP == < Traceparent: 00-3f2e2af5c071ca4cf5d05e50c30c2220-da5986c8b9d2f691-01
```

And on the service side:
```
== APP == Activate DemoActor actor!                                                                                                                                                                                                                                                                                           
== APP == has_value: False                                                                                                                                     
== APP == INFO:     127.0.0.1:59698 - "PUT /actors/DemoActor/1/method/GetMyData HTTP/1.1" 200 OK                                                                                                                                                                                                                              
== APP == INFO:     127.0.0.1:59725 - "GET /healthz HTTP/1.1" 200 OK                                        
```

**Comment by wcs1only** [comment]
> Hey @shlyopin, this is a known bug flagged out by a fellow developer in Dapr Discord Python-sdk group.

I'm not sure which known issue you are referring to @avvijeet ? This is an expected behavior, not a known issue, as far as I can tell.

**Comment by shlyopin** [comment]
> So in order to do what you are trying to do, you need to be talking to a dapr sidecar. This is what handles actor activation and enforces the property that only one actor can be activated at once. Try this instead:
> 
> ```
> dapr run --app-id demo-actor --app-port 3000 -- uvicorn --port 3000 demo_actor_service:app                            
> ```
> 
> ```
> dapr run -- bash -c 'curl -vX "PUT" "http://localhost:$DAPR_HTTP_PORT/v1.0/actors/DemoActor/1/method/GetMyData" -H "accept: application/json"'
> ```
> 
> When I run this I get:
> 
> ```
> == APP ==   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
> == APP ==                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying ::1...
> == APP == * TCP_NODELAY set
> == APP == * Connection failed
> == APP == * connect to ::1 port 59748 failed: Connection refused
> == APP == *   Trying 127.0.0.1...
> == APP == * TCP_NODELAY set
> == APP == * Connected to localhost (127.0.0.1) port 59748 (#0)
> == APP == > PUT /v1.0/actors/DemoActor/1/method/GetMyData HTTP/1.1
> == APP == > Host: localhost:59748
> == APP == > User-Agent: curl/7.64.1
> == APP == > accept: application/json
> == APP == > 
> == APP == < HTTP/1.1 200 OK
> == APP == < Server: uvicorn
> == APP == < Date: Thu, 05 Aug 2021 15:34:01 GMT
> == APP == < Content-Type: application/json; utf-8
> == APP == < Content-Length: 4
> == APP == < Traceparent: 00-3f2e2af5c071ca4cf5d05e50c30c2220-da5986c8b9d2f691-01
> ```
> 
> And on the service side:
> 
> ```
> == APP == Activate DemoActor actor!                                                                                                                                                                                                                                                                                           
> == APP == has_value: False                                                                                                                                     
> == APP == INFO:     127.0.0.1:59698 - "PUT /actors/DemoActor/1/method/GetMyData HTTP/1.1" 200 OK                                                                                                                                                                                                                              
> == APP == INFO:     127.0.0.1:59725 - "GET /healthz HTTP/1.1" 200 OK                                        
> ```

Thank you very much!!!
