### ISSUE TITLE
Type Annotations 

### ISSUE THREAD

**Issue by omidb** [dapr/python-sdk#254]
Is it possible to add type annotations to Actors functions in Python SDK: 
```python
async def set_my_data(self, data: object) -> None: #from this 
async def set_my_data(self, data: MoreSpecificClassName) -> None: #to this
########
await proxy.SetMyData({'data': 'new_data'}) #from this
await proxy.SetMyData(MoreSpecificClassName(data: 'new_data')) #to this
```
And will VS Code (or any other editor) intellisense work with it?

**Comment by wmeints** [comment]
I think you can, the type annotations have no effect at runtime.

**Comment by berndverst** [comment]
@omidb yes you can definitely use any types you want for the actor interfaces and then implementation in your actor.
