### ISSUE TITLE
Protobuf version

### ISSUE THREAD

**Issue by omidb** [dapr/python-sdk#271]
Can we match the version of 
https://github.com/dapr/python-sdk/blob/cf241a5926b2d8d139cfdf00a072eb4d6dcdb45d/setup.cfg#L25 

and 

https://github.com/dapr/python-sdk/blob/master/dev-requirements.txt#L10 

to be `3.17.3`?

**Comment by berndverst** [comment]
Thanks @omidb. Sure, no reason why we shouldn't do that. I had to make another fix and included this change within that PR.
