### ISSUE TITLE
[Question] Asyncio event loop in DaprInvocationHttpClient

### ISSUE THREAD

**Issue by wimvc1** [dapr/python-sdk#295]
Hi all,

I have a question/remark regarding the `DaprInvocationHttpClient` and specifically the `invoke_method` method.
Source: https://github.com/dapr/python-sdk/blob/18a609ac01b6b3c91f0a9e736dc24c4fa4ed9ac3/dapr/clients/http/dapr_invocation_http_client.py

Starting from line 96:
```
loop = asyncio.new_event_loop()
asyncio.set_event_loop(loop)

return loop.run_until_complete(make_request())
```

This creates a new event loop which seems to cause issues when using other libraries/frameworks which also use asyncio.
More specifically:
```
RuntimeWarning: coroutine 'DaprInvocationHttpClient.invoke_method.<locals>.make_request' was never awaited
Cannot run the event loop while another loop is running
```

To my understanding, there should be some extra logic to check if there is an existing event loop. If so, reuse that loop to handle the `make_request()` call.

Looking forward to your comments/suggestions.

PS:
When using `nest-asyncio`, this issues seems to be resolved but we would like to minimise the number of dependencies in our application.
https://pypi.org/project/nest-asyncio/

**Comment by wmeints** [comment]
Sounds like this could use an additional check. Async is always tricky.

**Comment by i-am-shodan** [comment]
This is still important
