### ISSUE TITLE
add support for Configuration API

### ISSUE THREAD

**Issue by dmitsh** [dapr/python-sdk#308]
The Configuration API feature has been implemented in Dapr runtime: https://github.com/dapr/dapr/pull/3606
It needs to be accessible via the SDK.

**Comment by chinzhiweiblank** [comment]
Good day all, I would like to take this on. I observe that the methods that need to be implemented are `GetConfigurationItem, GetConfigurationItems, SubscribeConfigurationItems, UnsubscribeConfigurationItems`.

**Comment by wcs1only** [comment]
@amulyavarote has already begun implementation on this, but if the two of you would like to collaborate, or trade work I'll leave that up to you.

**Comment by chinzhiweiblank** [comment]
No problem. I can take on this [issue ](https://github.com/dapr/python-sdk/issues/309) instead.

**Comment by omid-verneek** [comment]
Thanks for taking care of this. @amulyavarote any update on the state of the configuration API implementation?
