### ISSUE TITLE
Package tests/**/fake_*.py with Python package

### ISSUE THREAD

**Issue by guyzyl** [dapr/python-sdk#310]
## Describe the proposal
I'm currently working on Python code that uses Dapr, and to test my code I need to run/mock Dapr somehow.

If we package all the files under `tests/**/fake_*.py` into the published Dapr package, the mock classes would prove useful for applications that are dependent on Dapr and have unittesting in place.
It is also possible to create an additional Python package (`dapr-test`?) for packaging these file.

In my specific case, I need the `FakeDaprSidecar` class from `tests/clients/fake_dapr_server.py` for testing code that uses the Dapr client.
I'm open to working on this issue if the proposal is accepted.

**Comment by wimvc1** [comment]
Wouldn't it make more sense to mock the result returned by the Dapr client?
Because now you actually want/will test the Dapr client itself.

Also, might be related to #217

**Comment by guyzyl** [comment]
I want to test that my code behaves well in all of Dapr's scenarios.
It is possible to mock the results (and exceptions) returned by the Dapr client, but since a `FakeDaprSidecar` already exists I think it's a more elegant solution.

**Comment by wcs1only** [comment]
> I want to test that my code behaves well in all of Dapr's scenarios. It is possible to mock the results (and exceptions) returned by the Dapr client, but since a `FakeDaprSidecar` already exists I think it's a more elegant solution.

This is true, although it is tightly coupled with the existing unit tests, as it was never intended to be public. (See https://github.com/dapr/python-sdk/blob/master/tests/clients/fake_dapr_server.py#L178 for example)

I'm not opposed to making a dapr-tests package with a fake client in it, but it would need to be generic enough to mock arbitrary responses, etc. You could achieve the same end by just taking https://github.com/dapr/python-sdk/blob/master/tests/clients/fake_dapr_server.py#L1-L23 and implementing the behavior you want to test for each API call.
