### ISSUE TITLE
[Example] Azure Container App Demonstration

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/python-sdk#316]
## Describe the proposal

I would love to see an Azure Container App example as I am unable to get it to work myself 😅as far as I got, Container Apps seems to only support HTTP? While Python only supports gRPC?

For Container Apps a server thus has to start on HTTP and Dapr will register requests to it then, but we require the gRPC protocol in Python? @wcs1only can you help?

Jeff Hollan already provided an example in HTTP but he uses a hardcoded gRPC server (https://github.com/jeffhollan/grpc-sample-python)

**Comment by wcs1only** [comment]
python-sdk to daprd requests are indeed gRPC, but that should work without issue. Are you referring to having a GRPC vs HTTP ingress in your app? The python-sdk supports both scenarios, and we have extensions for flask and fastapi to that end:
https://github.com/dapr/python-sdk/tree/master/ext

Can you provide a little more detail about where you got stuck?

**Comment by XavierGeerinck** [comment]
Adding to this from the chat as well, I am trying to subscribe to a topic and receiving events from it. The code in the Runtime throwing the error is this:

![image](https://user-images.githubusercontent.com/591282/147980863-2bda2606-2609-434d-959b-659fe7dfe8db.png)

**Comment by XavierGeerinck** [comment]
Can be closed! Thanks a lot for the help!! https://github.com/dapr/python-sdk/blob/master/ext/dapr-ext-grpc/dapr/ext/grpc/app.py should sole it

**Comment by wcs1only** [comment]
Thanks, feel free to reach out on discord if you run into anything else, or open a new issue.
