### ISSUE TITLE
How do you reject work with the GRPC ext client?

### ISSUE THREAD

**Issue by renatolfc** [dapr/python-sdk#336]
In the [dapr-ext-grpc](https://github.com/dapr/python-sdk/tree/master/ext/dapr-ext-grpc) [documentation page](https://docs.dapr.io/developing-applications/sdks/python/python-sdk-extensions/python-grpc/), we see the following example for subscribing to `TOPIC_A` on the `pubsub` publish subscribe component.

```python
@app.subscribe(pubsub_name='pubsub', topic='TOPIC_A')
def mytopic(event: v1.Event) -> None:
    print(event.Data(),flush=True)
```

The document doesn't say how one `ACK`s a message. Are messages `ACK`ed when the decorated function (`mytopic`, in the example above) is called, or when it returns?

If a message is only `ACK`ed when the decorated function returns, how do I prevent redelivery when the decorated function needs to do a long-running operation? Or how do I reject work until a long-running operation completes?

What happens if an exception is raised from the decorated function? Will dapr try to redeliver the message?

Thanks!

**Comment by renatolfc** [comment]
After some local experimentation, it seems that:

 1. The avoid retried deliveries, the decorated function should return as soon as it determines it can act upon a received event (seems to be similar to returning a `200` using the HTTP API)
 2. If an exception is raised from the decorated function, dapr will try to deliver the message at a later time (Seems to be similar to returning something `!= 200` in the HTTP API)

Is this description correct?

**Comment by wcs1only** [comment]
One approach would be to allow the callback function to return a TopicEventResponse object.

**Comment by renatolfc** [comment]
As a user, I like that suggestion. Should I try contributing a PR?

**Comment by renatolfc** [comment]
#336 is my attempt at solving this issue following @wcs1only's suggestion.

Please let me know if it needs improvements, as it'd be super nice for me to be able to intruct dapr to retry/reject messages using the grpc client.
