### ISSUE TITLE
Remove extra return statement

### ISSUE THREAD

**Issue by letmerecall** [dapr/python-sdk#34]
## Description

There is an unnecessary return statement in line 32 of `/invoke-simple/invoke-receiver.py`
https://github.com/dapr/python-sdk/blob/2a6701d0abe9d5fb89bb67e16fda84e845bd063f/examples/invoke-simple/invoke-receiver.py#L32

## How to fix

Removing lines 31-32 will do just fine.

**Comment by amanbha** [comment]
@letmerecall Would you like to contribute and submit a PR for it?

**Comment by pruthvidhodda** [comment]
Sorry, this is already being fixed in [this](https://github.com/dapr/python-sdk/pull/28) PR

**Comment by letmerecall** [comment]
That's great @pruthvidhodda  👍
