### ISSUE TITLE
HTTP: Output Binding Support

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/python-sdk#347]
## Expected Behavior

It appears that we cannot invoke Output Bindings through HTTP, making it hard to develop applications on Container Apps as it does not support gRPC yet. When trying to execute a Sidecar command I get the below

```json
{\"created\":\"@1642700196.902461594\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3134,\"referenced_errors\":[{\"created\":\"@1642700196.902460394\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/lib/transport/error_utils.cc\",\"file_line\":163,\"grpc_status\":14}]}"}
```

**Comment by berndverst** [comment]
@XavierGeerinck please file with Container Apps https://github.com/microsoft/azure-container-apps. The Dapr Client SDK exclusively uses gRPC as the mechanism to call the Dapr Sidecar. There are no plans to support HTTP as this is an internal implementation detail.
