### ISSUE TITLE
Environment variables: Sync with the latest doc

### ISSUE THREAD

**Issue by anhldbk** [dapr/python-sdk#350]
## Overview

- I made [the PR](https://github.com/dapr/docs/pull/1835) to correct [environment variables] (https://docs.dapr.io/reference/environment/).

- Our Python SDK has variables that inconsistent with the new documentation. See [python-sdk/dapr/conf/global_settings.py](https://github.com/dapr/python-sdk/blob/6d7d9400736d2c58901c7b49f666a159f987e789/dapr/conf/global_settings.py)

- IMHO, the current implementation does not support auto-completion while editing code

```python
# dapr/conf/__init__.py
class Settings:
    def __init__(self):
        for setting in dir(global_settings):
            default_value = getattr(global_settings, setting)
            env_variable = os.environ.get(setting)
            setattr(self, setting, env_variable or default_value)

    def __getattr__(self, name):
        return getattr(self, name)


settings = Settings()

# other module to use the settings
from dapr.conf import settings
http_timeout_seconds = settings.DAPR_HTTP_TIMEOUT_SECONDS
```

## The proposal

I'm gonna make a PR to fix the inconsistencies. 

To support auto-completion, should I refactor the code to use enum?

```python
from enum import Enum, auto

class Env(Enum):
    def _generate_next_value_(name, start, count, last_values):
        return os.environ.get(name)
    def __str__(self):
        return self.value
    HTTP_APP_PORT = auto() or 3000
    DAPR_HTTP_PORT = auto() or 3000
    GRPC_APP_PORT = auto() or 3010
```

**Comment by anhldbk** [comment]
@berndverst @wcs1only PTAL

**Comment by berndverst** [comment]
Is there a way we can also support the existing wrongly named environment variables? We should try to maintain that for backwards compatibility.

I'm fine with the enum approach.
