### ISSUE TITLE
Passing APIRouter tags to the fast-api DaprActor

### ISSUE THREAD

**Issue by yairsimantov20** [dapr/python-sdk#401]
## Describe the proposal
The routes from the DaprActor appears in the openapi documentation so i think the library should allow to pass the router tags or supply default tags in order to differentiate the Actor routes from the application routes
The new Actor should look like:
```python
class DaprActor(object):
    def __init__(self, app: FastAPI, router_tags: List[str]): <----- New
        self._dapr_serializer = DefaultJSONSerializer()
        self._router = APIRouter(tags=tags) <----- New
        self.init_routes(self._router)
        app.include_router(self._router)
......
```
![image](https://user-images.githubusercontent.com/63305203/166132585-31b9fa5b-7b95-491b-abc5-c9b1bc001323.png)
__Will now look like__
![image](https://user-images.githubusercontent.com/63305203/166132593-6dfddd8b-14f3-4b73-a89e-81fb45ee26ef.png)

**Comment by yairsimantov20** [comment]
I think the best solution will be a list with a default value of 'Actor'
and the code will look like
```python
DEFAULT_ACTOR_ROUTER_TAGS = ['Actor']

class DaprActor(object):
    def __init__(self, app: FastAPI, router_tags: Optional[List[str]] = None): <----- New
        self._dapr_serializer = DefaultJSONSerializer()
        router_tags = router_tags if router_tags is None else DEFAULT_ACTOR_ROUTER_TAG
        self._router = APIRouter(tags=tags) <----- New
        self.init_routes(self._router)
        app.include_router(self._router)

**Comment by berndverst** [comment]
@yairsimantov20 are these tags used for anything other than generating documentation? I want to make sure this doesn't cause any behavioral changes for anyone.

**Comment by yairsimantov20** [comment]
Used only for the swagger docs. The swagger docs don't show anything else about it
https://fastapi.tiangolo.com/tutorial/bigger-applications/?h=tags#add-some-custom-tags-responses-and-dependencies
https://fastapi.tiangolo.com/tutorial/metadata/?h=tags#use-your-tags

**Comment by berndverst** [comment]
@yairsimantov20 take a look at the linked PR. I also added router tags to the PubSub subscription.

I explicitly added the tags to the specific routes instead of the entire router. This is so the same Fast API instance can be used everywhere and we don't accidentally overwrite any tags of existing routes.

**Comment by yairsimantov20** [comment]
@berndverst 
I've commented on your pull request
if there is something you don't agree with then please let me know (Its my first pull request in an open source)
