### ISSUE TITLE
Add more comments to codes which allows sphinx to auto-generate python docs.

### ISSUE THREAD

**Issue by youngbupark** [dapr/python-sdk#41]
## Describe the proposal

- [ ] Add more code level comments
- [ ] Generate sphinx docs

related to #40

**Comment by chinzhiweiblank** [comment]
I can help with this. Which modules do you need documented first?

**Comment by youngbupark** [comment]
> I can help with this. Which modules do you need documented first?

Thanks for your interest. There are many codes which miss the comments. It may need to understand the code.

So I am suggesting to add sphinx doc generation environment to tox and add napoleon extension because this code uses google comment style.  Can you contribute this one first? if you want to do it, please file new issue separately.

**Comment by chinzhiweiblank** [comment]
No problem! I already started the sphinx doc generation.
