### ISSUE TITLE
Change configuration API response to dictionary

### ISSUE THREAD

**Issue by amulyavarote** [dapr/python-sdk#411]
## Describe the proposal

Change the configuration API response to handle dictionary.
Main issue in dapr/dapr in pasted here.
https://github.com/dapr/dapr/issues/4556

**Comment by berndverst** [comment]
Depends on https://github.com/dapr/dapr/pull/4695 which is not likely to be released in dapr/dapr v1.9

**Comment by berndverst** [comment]
Was addressed here, so this can make it into 1.8 (with Dapr 1.9 release). https://github.com/dapr/dapr/pull/5083
