### ISSUE TITLE
Add distributed lock API support

### ISSUE THREAD

**Issue by amulyavarote** [dapr/python-sdk#412]
## Describe the proposal

Add methods for distributed lock API.

Main Issue: https://github.com/dapr/dapr/issues/3549

**Comment by berndverst** [comment]
@tmacam this might be a good issue for you to tackle to learn about the Python SDK

**Comment by berndverst** [comment]
This is a gRPC - the code will likely go here:
https://github.com/dapr/python-sdk/blob/master/dapr/clients/grpc/client.py

Unit tests are in `/tests`

`Examples` folder acts as both example and integration tests (see `Readme.md` raw source for how this is done in each example)
