### ISSUE TITLE
Mypy stubs

### ISSUE THREAD

**Issue by Trolldemorted** [dapr/python-sdk#456]
You are using mypy already, could you publish mypy stubs for downstream projects?

**Comment by berndverst** [comment]
I don't know what that involves. Can you link to some docs or make a PR @Trolldemorted ?

**Comment by berndverst** [comment]
@Trolldemorted since you need the source directory to see the stub files anyway, I think it makes more sense if you generate these yourself. You can always check out a release branch or release tag before doing so.

```
pip3 install mypy
stubgen -o stubs/dapr
stubgen -o stubs/dapr-ext-grpc ext/dapr-ext-grpc
stubgen -o stubs/dapr-ext-fastapi ext/dapr-ext-fastapi
stubgen -o stubs/flask_dapr ext/flask_dapr
```

**Comment by Trolldemorted** [comment]
Sorry for the long delay.

Generating stubs myself is not really a viable solution, since I'd have to redo that everytime we update the dapr bindings. However, if your type hints are correct, all you should need to do is add an empty `py.typed` file to your package as described in [PEP 561](https://peps.python.org/pep-0561/#packaging-type-information).

It is hacktoberfest anyway, I'll see whether I can send you a PR :)

**Comment by berndverst** [comment]
Sounds good! Happy to accept a PR for this!

**Comment by Trolldemorted** [comment]
#475 is awaiting a review, looks like it works fine

**Comment by berndverst** [comment]
@Trolldemorted done!

**Comment by Trolldemorted** [comment]
I am sorry but I have to bother you again - you have labeled the issue, not the PR 😇

**Comment by berndverst** [comment]
@Trolldemorted :D my bad.
