### ISSUE TITLE
Relax protobuf version requirement

### ISSUE THREAD

**Issue by AlexanderLanin** [dapr/python-sdk#470]
## Describe the proposal
Currently dapr package requires protobuf == 4.21.6, which is very very specific and makes life difficult when handling multiple packages which all require different versions.

I guess/hope this can be relaxed?!
I don't know to which extend, e.g.
* \>=4 <5
* \>=3 <5
* \>= 4.21 <4.22

**Comment by berndverst** [comment]
I'll have to make it 4.21 minimum. Will update this.

https://developers.google.com/protocol-buffers/docs/news/2022-05-06
