### ISSUE TITLE
Wrong type for get_configuration keys

### ISSUE THREAD

**Issue by ryou90** [dapr/python-sdk#491]
## Expected Behavior

Expecting _keys_ parameter in get_configuration is List[str] or Tuple[str,...]

## Actual Behavior

Type definition for _keys_ parameter in get_configuration is _str_, but all examples using list parameters, e.g. ['key1']. 

## Steps to Reproduce the Problem

Look at source code.

## Release Note

RELEASE NOTE: **FIX** Wrong typing for keys param in get_configuration

**Comment by berndverst** [comment]
@ryou90 do you want to open a PR for this and fix it? :)
