### ISSUE TITLE
Missing dependency 'typing_extensions'

### ISSUE THREAD

**Issue by worming004** [dapr/python-sdk#538]
## Expected Behavior

When installing dapr sdk, a project using sdk should run with all required dependencies

## Actual Behavior

A project using the sdk do not run because of a missing dependency

## Steps to Reproduce the Problem

* Use a fresh computer without any pre-installed python libraries
* Follow the doc until https://docs.dapr.io/getting-started/quickstarts/pubsub-quickstart/#step-4-publish-a-topic
* Following the step 4, the application cannot start
<img width="1792" alt="Screenshot 2023-03-09 at 07 44 06" src="https://user-images.githubusercontent.com/23192591/223942263-fec2c26f-f454-4ec5-8d1c-1e9c3d736319.png">

## Release Note

RELEASE NOTE: **FIX** dependencies resolution

## Note for maintainers

I am not a python developer, I do not know how pip resolve dependencies. So I cannot propose quickly a PR to resolve this issue.
Anyway, thanks for your job !

**Comment by berndverst** [comment]
Sorry for the delay - I am releasing Dapr Python SDK 1.9.1 right now to address this.

**Comment by tmacam** [comment]
Created #546 to avoid this in the future.

This was closed by #545, right?

**Comment by berndverst** [comment]
> Created #546 to avoid this in the future.
> 
> This was closed by #545, right? And #544 is a duplicate of this one.

Correct. This is resolve in SDK 1.9.1
