### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by ryou90** [dapr/python-sdk#539]
MAINTAINER EDIT: The issue here is that the recursion limit only is encountered for attributes that are not actually supported by the settings class. For unknown attributes we have no default, and hence the error.

## Expected Behavior

I want to retrieve an env variable from the dapr.config.settings class.  If the variable is not present, an attribute error should be issued.

E.g.
```python
from dapr.conf import settings

x = settings.APP_PORT # Not exist -> throw recursion error
```

## Actual Behavior

When the variable not exists, a maximum recursion error is thrown and not a attribute error. This happens because the settings class  use __getattr__ method to lookup for non existing env variables. Within the method, getattr(..) is called, which caused a new recursive call.

The problem can be easily solved by removing the __getattr__ method.

## Steps to Reproduce the Problem

Test example code.

## Release Note

RELEASE NOTE:
**Fix** RecursionError when calling non-existing env variable from settings class

**Comment by berndverst** [comment]
`APP_PORT` is not a supported setting in this SDK. There is `HTTP_APP_PORT` and `GRPC_APP_PORT`.

See
https://github.com/dapr/python-sdk/blob/a1aa2cb17a7c16c3e5091c915ca48baeaea95910/dapr/conf/global_settings.py#L18-L29
