### ISSUE TITLE
Adjust validation workflows to reproduce "new install environment"

### ISSUE THREAD

**Issue by tmacam** [dapr/python-sdk#546]
## Describe the proposal

While addressing #538 and #544 (PR #545) we noticed that our validation workflows are not reproducing an environment that matches that required to run a new application setup. Instead it matches that of our suggested development environment. While those are similar they are not necessarily the same: the dependencies required to run Dapr python application (defined in `setup.cfg`) _should be_ a subset of the development one (defined in `dev-requirements.txt`), but that isn't guaranteed.

The proposal is to add a validation step that ensures that a simple sample application that requires Dapr, created in a clean virtual environment, can run. This simple test should avoid errors like #538.

Additionally, it would be great if we could also ensure that install dependencies are a proper subset of the ones defined in `dev-requirements.txt` as part of the same validation step. It is a sanity check more than anything else but, again, it would ensure sanity in split dev-install dependencies duo.

**Comment by berndverst** [comment]
After some investigation the opposite is true @tmacam.

Everyone should use `pip3 install -e .` to install the package and its dependencies locally. `dev-requirements.txt` should only contain things strictly required in unit tests or for generating protos.

`dev-requirements.txt` should neither be a superset nor a subset of `setup.cfg`. These things should be completely distinct.

**Comment by berndverst** [comment]
I think this is actually fixed at the moment.
