### ISSUE TITLE
Preview Feature Support: Add Actor State TTL support

### ISSUE THREAD

**Issue by JoshVanL** [dapr/python-sdk#560]
Add first class API support for Actor State TTL https://github.com/dapr/dapr/issues/5899

A dedicated function to Actor State should be created. Psudo code: `func (key string, value string, ttl duration)`. It should be made clear in the SDK documentation/comments that users should always use this function, unless they have specifically created some kind of Actor State clean up out of band of Dapr or don't have an issue with the Actor State store keep state and grow "forever".

Please see the [go-sdk](https://github.com/dapr/go-sdk/pull/383/files) for implementation reference.

**Comment by JoshVanL** [comment]
UPDATE: Due to the nature of the current implementation of write through caching of actor state and the unavailability of the real TTL expire time of state keys, SDKs will have an inconsistent view of the world when it has a cold cache and the state store has TTL keys. The TTL functionality has been put behind a feature gate in daprd. See https://github.com/dapr/dapr/pull/6400 for more details. This feature is expected to be moved to GA in 1.12.

**Comment by berndverst** [comment]
At this point the SDK support will not be added until Dapr 1.12 (SDK release 1.11)

**Comment by dasanind** [comment]
@berndverst Is this issue still needed to be worked on?
