### ISSUE TITLE
Sample k8s config using wrong port.

### ISSUE THREAD

**Issue by softnado** [dapr/python-sdk#592]
https://github.com/dapr/python-sdk/blob/5904cff8c50aeaf578b870b010b6b8e511765d23/examples/grpc_proxying/deploy/invoke-receiver.yaml#L39

Should the port mentioned here be 50051?

**Comment by berndverst** [comment]
This example indeed seems to be wrong. But instead, please make the `app-port` 3000. 50051 sounds too similar to the Dapr sidecar gRPC server meant for SDK to sidecar communication.

Happy to accept a PR to change the `app-port` to 3000 here.
