### ISSUE TITLE
Support for `DAPR_API_TOKEN` in the Workflow SDK

### ISSUE THREAD

**Issue by alicejgibbons** [dapr/python-sdk#594]
## Expected Behavior
Set the `DAPR_API_TOKEN` environment variable and expect the Python Workflow SDK to respect and authenticate all Dapr API calls with the value.

## Actual Behavior
The `DAPR_API_TOKEN` environment variable value is not correctly passed to the durable task python library for connecting to the Dapr sidecar.

## Steps to Reproduce the Problem
1. Set `DAPR_API_TOKEN` environment variable
2. Run the Python workflows quickstart: https://github.com/dapr/quickstarts/tree/master/workflows/python/sdk
3. Get `Unauthorized` error from Python durable task library. 
![image](https://github.com/dapr/python-sdk/assets/14792988/3bcc2638-6df5-4604-85e4-8aff0669c76d)

## Release Note

RELEASE NOTE:**ADD** Support for Dapr API token auth in Workflows API.

**Comment by berndverst** [comment]
@DeepanshuA can you please give an update here? Is there a PR in durable task python yet? And can we see a PR update here soon? This is the only thing that is holding up the SDK release and I'd like the PR review to not be rushed.
