### ISSUE TITLE
Document That Users Can Self-Assign Issues

### ISSUE THREAD

**Issue by cicoyle** [dapr/python-sdk#602]
Please link to the [daprbot documentation](https://docs.dapr.io/contributing/daprbot/) inside the contributing.md file, so that users know what Github commands they can run in this repo. Based on the dapr-bot.yml they can run the [/assign to self assign issues](https://github.com/dapr/python-sdk/blob/master/.github/workflows/dapr-bot.yml#L29) in this repo.

**Comment by berndverst** [comment]
Feel free to open a PR against the documentation to link to this.
