### ISSUE TITLE
Check outbound healthz endpoint on sidecar wait

### ISSUE THREAD

**Issue by mukundansundar** [dapr/python-sdk#611]
## Feature request

Similar to dotnet sdk check the outbound healthz endpoint for checking if sidecar is ready. 
https://github.com/dapr/dotnet-sdk/blob/master/src/Dapr.Client/DaprClientGrpc.cs#L1790

Even if the port is open, Dapr might not be ready yet. 

## Current behavior
Python only waits to check if the port is available and socket connection can be created. 
https://github.com/dapr/python-sdk/blob/master/dapr/clients/grpc/client.py#L1431

RELEASE NOTE:

**Comment by mukundansundar** [comment]
@dapr/maintainers-python-sdk For this one, can I modify the existing `wait` method in the gRPC clients (sync and async), to directly check against the HTTP endpoint `"/v1.0/healthz/outbound"` instead of the the socket check that we do right now. 
This will change the behavior of `wait` method, but will not be a breaking change since this was supposed to be the actual health check and current implementation is considered a bug.

**Comment by mukundansundar** [comment]
If the `appconfig` Dapr configuration is not found in `default` namespace for some reason, the `dapr.io/config` parameter will not be set and skipped emitting a warning: 
```
⚠  Dapr configuration "appconfig" not found in namespace "default". Skipping annotation "dapr.io/config"
```

**Comment by mukundansundar** [comment]
> Additionally, you also need to use this in the Dapr Actor Client and Dapr Service Invocation Client.

Based on the current usages, I only see the `wait` method being called in examples. Can you tell me why we need to use this in Actor Client and Service Invocation Client?

**Comment by berndverst** [comment]
> > Additionally, you also need to use this in the Dapr Actor Client and Dapr Service Invocation Client.
> 
> Based on the current usages, I only see the `wait` method being called in examples. Can you tell me why we need to use this in Actor Client and Service Invocation Client?

It might be nice for anything which talks to the sidecar to first wait to make sure Dapr is ready. So if it's missing it should be added I think.

**Comment by elena-kolevska** [comment]
Done in https://github.com/dapr/python-sdk/pull/670
