### ISSUE TITLE
Argument in client constructor overrides http endpoint

### ISSUE THREAD

**Issue by elena-kolevska** [dapr/python-sdk#620]
## Expected Behavior

The http endpoint defined by the environment variable `DAPR_HTTP_ENDPOINT` or   `DAPR_RUNTIME_HOST` plus `DAPR_HTTP_PORT` should be used for http service invocation and actors.

## Actual Behavior
The http endpoint defined by the environment variable `DAPR_HTTP_ENDPOINT` or   `DAPR_RUNTIME_HOST` plus `DAPR_HTTP_PORT` is overridden by the gRPC address argument passed in the client constructor. 
I introduced this bug myself in https://github.com/dapr/python-sdk/pull/597

## Steps to Reproduce the Problem
Run the invocation examples in `examples/invoke-http/invoke-caller.py`, but update the client initialisation with an argument:
```python
...
with DaprClient("localhost:50001") as d:
...
```

## Release Note
RELEASE NOTE: **FIX** Fixes http endpoint being overwritten by address argument in constructor

**Comment by artursouza** [comment]
I don't think this is a bug. The proposal says that arguments passes in the code takes precedence over the env variables.

**Comment by artursouza** [comment]
I understand the issue now, thanks for fixing this.
