### ISSUE TITLE
allow optional explicit naming of workflow and activity names

### ISSUE THREAD

**Issue by bkcsfi** [dapr/python-sdk#623]
## Describe the proposal

It would be helpful to allow users to explicitly declare the name of an activity or workflow when they are registered, and the name of a called activity, as an alternative to using the activity or workflow function `__name__`.

Consider an application that can download and process files from various sources, A, B and C. In the future, additional sources will be added.

Here's one way to lay out the code.

```
/src
  /interface
     /A
        /activities.py
     /B
        /activities.py
     /C
        /activities.py
     /D
        /activities.py
```

Suppose each source has the same nominal activity `get_input_file`

I think it would be cleaner to use these activities this way:

```python
from interface import A, B, C, D
...
input_module = A if input_type == 'A' else B
file_result = yield ctx.call_activity(input_module.get_input_file)
...
```

Currently the activity name will be taken from the function name, there's no way to have the same activity in different modules.

Therefore I have to write code like this instead:

```python
from interface import A, B, C, D
...
if input_type == 'A':
    file_result = yield ctx.call_activity(A.get_input_file_A)
else:
    file_result = yield ctx.call_activity(B.get_input_file_B)
...
```

If an optional name can be explicitly passed to call_activity, register_activity and register_workflow, then users could  manage  complicated workflows in a tidier way.

for example, I would write a decorator to assign an `__registered_name` attribute to my activity functions.

Then I would use a wrapper function to call activities, something like:

```python

def call_activity(ctx, activity, *arg):
   yield ctx.call_activity(activity.__registered_name, *arg)

...

from interface import A, B, C, D
...
input_module = A if input_type == 'A' else B
file_result = yield call_activity(ctx,input_module.get_input_file)
...
```

**Comment by mukundansundar** [comment]
PR #651 should address this issue.
