### ISSUE TITLE
[WORKFLOW SDK FEATURE REQUEST] more samples for dapr workflow

### ISSUE THREAD

**Issue by lucus-sun** [dapr/python-sdk#637]
## Describe the WORKFLOW SDK feature

We only have a basic workflow sample that call several activities one by one, it's hard to learn how to use other advanced features. We should have more example codes including:

1. How to use durable timers in workflow?
2. How to use child workflows?
3. All these [workflow patterns](https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-patterns/) should be in the sample folder of the python sdk with a main function that can run directly.

Without these examples, it's very hard to learn how to use dapr workflow. Hope this can be scheduled in v1.13.

**Comment by cgillum** [comment]
The workflow patterns examples have already been merged into this repo: https://github.com/dapr/python-sdk/pull/575.

You can find the workflow patterns samples here: https://github.com/dapr/python-sdk/tree/main/examples/workflow

I don't think there is currently a child workflow sample for Python, however. This is something that can be added.

**Comment by rabollin** [comment]
We do have multiple samples for Workflow scenarios in different repos that usually one can refer in addition to the pattern code samples shown in dapr docs here: https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-patterns/

Different DAPR repos where you can find the samples: 

1. https://github.com/dapr/samples 
2. https://github.com/dapr/python-sdk/tree/main/examples/workflow
3. https://github.com/dapr/quickstarts

**Comment by cgillum** [comment]
The Python Workflow demo that I created for KubeCon can be found here: https://github.com/dapr/samples/tree/master/workflow-orderprocessing-python
