### ISSUE TITLE
Convenient layer for gRPC APIs

### ISSUE THREAD

**Issue by youngbupark** [dapr/python-sdk#67]
## Describe the proposal

Create convenient layer for gRPC API.  This is to create the convenient layer for gRPC API.

Reference:
JAVA SDK - https://github.com/dapr/java-sdk/blob/master/sdk/src/main/java/io/dapr/client/DaprClient.java
https://github.com/dapr/java-sdk/blob/master/sdk/src/main/java/io/dapr/client/DaprClientGrpc.java

Location: dapr/clients/grpc

**Comment by youngbupark** [comment]
@chinzhiweiblank if you want to contribute to the convenient layer for gRPC API. Please refer to JAVA SDK that I refer to :)

**Comment by chinzhiweiblank** [comment]
No problem I'll look into this after the non-Actor APIs PR.

**Comment by chinzhiweiblank** [comment]
No problem. I can take this up.

**Comment by youngbupark** [comment]
> No problem. I can take this up.

Thanks I assigned it to you. Please create small PRs. for example, one pr is creating wrappers of state related apis. second pr is create wrapper for bindings. and so on. We must have the proper tests for each implementation.

**Comment by chinzhiweiblank** [comment]
@youngbupark Is this for the actor client?

**Comment by youngbupark** [comment]
> @youngbupark Is this for the actor client?

No this is only for Dapr API. No grpc apis for actor now. Have you tried to run the samples repo codes to understand the each building blocks? Otherwise, Without understanding apis, it would be difficult to work on this item. Please try out samples first and then understand java api design that I refer to.

**Comment by youngbupark** [comment]
@chinzhiweiblank I have separated work items to deliver the features iteratively. I will write up the initial code for invoke service api soon. If you're unfamiliar with dapr apis, please play with some of examples and samples.

**Comment by chinzhiweiblank** [comment]
@youngbupark no problem I started with the statestore apis

**Comment by youngbupark** [comment]
## Problems

* Developers need to understand how to create gRPC server and use gRPC client 
* Developers need to change their service codes if dapr API has a breaking change
* Developers need to know how to pass request metadata and extract headers/trailers from response.
* Developers need to understand how to serialize and deserialize protobuf message if they want to use their own protocol buffer message.
* Developers need to implement their own routing logics to support multiple service invoke methods/topics/bindings.

## Goals

* Provide the developer-friendly API set to create user applications easier 
* Encapsulate gRPC server/client handling codes

## Proposed convenient Layer for Dapr API

### Summary

* Remove gRPC client handling code 
* Provide seamless way to handle bytes data and protocol buffer messages (encapsulate protobuf serialization and deserialization)
* Provide seamless way to handle metadata of request and headers/trailers of response.
* Help users to create more python-like code

#### Example: Dapr InvokeService API

Convenient layer for Dapr Client API provides context manager so that user can use `with` python keyword and it handles Dapr gRPC client connection. Therefore, user doesn't need to know how to connect Dapr gRPC server and when to disconnect Dapr gRPC server.

The convenient layer encapsulates gRPC connection implementation which enables Dapr to run in python interactive command mode without creating the application:

```
>>> import dapr
>>> with dapr.Dapr() as d:
...     resp = d.invoke_service('callee', 'method', b'data')
...     resp.bytesdata
b'return_data'
>>>
```

**Current implementation:**
https://github.com/dapr/python-sdk/blob/e4ade372fc2c4aad430b9ea961efdf855d10da03/examples/invoke-custom-data/invoke-caller.py#L1-L37

**Proposed:**

```python
from dapr import Dapr

import proto.response_pb2 as response_messages

with Dapr() as d:
	# Create a typed message with content type and body
	resp = d.invoke_service(
		id='invoke-receiver',
		method='my_method',
		data=b'SOME_DATA',
		content_type='text/plain; charset=UTF-8',
	)
	res = response_messages.CustomResponse()
	resp.unpack(res)
	# Print Result
print(res, flush=True)
```

#### More examples

The example calls `callee` service with bytes data, which implements grpc appcallback:

```python
from dapr import Dapr

with Dapr() as d:
	resp = d.invoke_service(
		id='callee',
		method='method',
		data=b'message',
		content_type='text/plain',
		metadata=(
			('header1', 'value1')
		),
	)

	# resp.bytesdata includes the bytesdata array.
	# resp.content_type specifies the content type of resp.bytesdata.
	# Thus, resp.bytesdata can be deserialized properly.
	
	# resp.headers['grpc-trace-bin'] to access response headers.
	# resp.trailers['trailer1'] to access response trailers.
```

When sending custom protocol buffer message object, it doesn't requires content_type:

```python
from dapr import Dapr

req_data = dapr_example_v1.CustomRequestMessage(data='custom')
with Dapr() as d:
	resp = d.invoke_service(
		id='callee',
		method='method',
		data=req_data,
		metadata=(
			('header1', 'value1')
		),
	)
	# Create protocol buffer object
	resp_data = dapr_example_v1.CustomResponseMessage()
	# Deserialize to resp_data
	resp.unpack(resp_data)
```

The example calls `callee` service which implements http appcallback:

```python
from dapr import Dapr

with Dapr() as d:
	resp = d.invoke_service(
		id='callee',
		method='method',
		data=b'message',
		content_type='text/plain',
		metadata=(
			('header1', 'value1')
		),
		http_verb='POST',
		http_querystring=(
			('key1', 'value1')
		),
	)
	# resp.bytesdata includes the bytesdata array.
	# resp.content_type specifies the content type of resp.bytesdata.
	# Thus, resp.bytesdata can be deserialized properly.
```

## Opportunties

* Jupyter notebook integration - If dapr runs with jupyter notebook side by side, users can save the note book data to its statestore and store data to blob storage via output binding.
