### ISSUE TITLE
[WORKFLOW SDK BUG] None Check is missing in the WorkflowState to_json

### ISSUE THREAD

**Issue by amichel** [dapr/python-sdk#691]
## Expected Behavior

Always get a valid JSON using the to_json method

## Actual Behavior
When workflow completes successfully, to_json (and __str__) methods fail with 
**Exception calling application: 'NoneType' object has no attribute 'message'**

## Steps to Reproduce the Problem
1. Run any Workflow to completion, such that failure_details is absent from the workflow state.
2. Call either get_state or wait_for_workflow_completion
3. Call to_json on the returned state object

## Release Note
RELEASE NOTE:

**Comment by elena-kolevska** [comment]
LGTM. It's a simple enough change, I also confirmed it locally, but I would feel better if we added a little test for it, though.

**Comment by berndverst** [comment]
@akshaya-a please reply on this issue with `/assign` to get credit for addressing it.

**Comment by berndverst** [comment]
`dapr-ext-workflow` release candidate version `v0.5.0rc1` with this change is now released. FYI
