### ISSUE TITLE
Support for user supplied actor_factory callable 

### ISSUE THREAD

**Issue by ksachdeva** [dapr/python-sdk#713]
## Describe the feature

`ActorRuntimeContext` has the support to take the user-supplied callable that would instantiate the Actor object. However, the classes (e.g. `ActorRuntime` and various `register_actor` functions in the extensions (flask and fastapi)) do not expose the possibility of providing the callable from the user code.

## Release Note

RELEASE NOTE: **ADD** Support for user-supplied actor_factory callable.

**Comment by berndverst** [comment]
Can you go into more detail as to why we would want this? And can you see whether any of the other SDKs support this?

**Comment by ksachdeva** [comment]
This would enable dependency injection in the Actors.

See an example of it in the .net SDK 
https://github.com/dapr/dotnet-sdk/blob/master/examples/Actor/DemoActor/DemoActor.cs
