### ISSUE TITLE
[Feature] Health checks for `dapr-ext-grpc`

### ISSUE THREAD

**Issue by evhen14** [dapr/python-sdk#722]
I see that the HealthCheck call returns `Code: Unimplemented, Message: Method Not Found` and I see `Method Not Implemented` in the [source code](https://github.com/dapr/python-sdk/blob/main/dapr/proto/runtime/v1/appcallback_pb2_grpc.py#L243)

The call is made from the dapr code directory for proto files: `grpcurl -plaintext -import-path . -proto dapr/proto/runtime/v1/appcallback.proto localhost:50051 /dapr.proto.runtime.v1.AppCallbackHealthCheck/HealthCheck` 

In the [documentation](https://docs.dapr.io/operations/resiliency/health-checks/app-health/#grpc), we have a statement: 

> When using gRPC for the app channel (app-protocol set to grpc or grpcs), Dapr invokes the method /dapr.proto.runtime.v1.AppCallbackHealthCheck/HealthCheck in your application. Most likely, you will use a Dapr SDK to implement the handler for this method.

Does DaprD call this method for health checks? What does it do when it gets `Unimplemented` and what does it do when no response is there, for example, when `App().run(50051)` stopped (in my case it's run in a separate thread). 

In Golang SDK, I even see [a way](https://github.com/dapr/go-sdk/blob/33180dd89a463a16781c02f60cbb909e8ccb6aef/service/grpc/health_check.go#L27) to add custom health checks, is there a plan to support it in the Python SDK

Thx in advance!

**Comment by evhen14** [comment]
I'm looking into adding an implementation where developers can add a health check callback, e.g. `dapr_app.register_health_check(health_check_func)` 

Let me know what you think

**Comment by berndverst** [comment]
Will be in `dapr-ext-grpc` 1.14. That might not be the next version number, but I will synchronize the version name to be aligned with the Dapr runtime versions so it's easier to tell which runtime version will work with this feature for sure.
