### ISSUE TITLE
Please mark Dapr-dev Python >= 3.7 instead of 3.8

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/python-sdk#82]
## Describe the proposal

I would like to see Python >= 3.7 supported instead of 3.8 (which is cutting edge), seeing that a lot of libraries are still depending on 3.7 at the moment.

> Note: Currently I manually clone and install it locally and it's working on Python 3.7 for me

**Comment by youngbupark** [comment]
ok make sense. I will make a change.

**Comment by XavierGeerinck** [comment]
Awesome, thanks a lot! :) this will specifically enable tensorflow 1.14.0 to be utilized!

**Comment by youngbupark** [comment]
> Awesome, thanks a lot! :) this will specifically enable tensorflow 1.14.0 to be utilized!

Nice! 

BTW, I am working on convenient layer for app callback as well. Then we do not need to implement grpc server either. 

This is an example:

```python
from dapr import App, CallbackResponse

app = App()

@app.method(name='my-method')
def mymethod(metadata, data, content_type, *http_args) -> CallbackResponse:
    print(metadata, flush=True)
    print(data, flush=True)

    return b'INVOKE_RECEIVED'

app.daprize()

app.wait_until_stop()
```

**Comment by XavierGeerinck** [comment]
Awesome work! This seems really useful 😊 currently I switched back the HTTP layer as well seeing the amazing speed, might switch back to gRPC after a while.

P.S. Seeing an odd bug that "might" have to do with Dapr at high velocity of calls, I'll post the relevant Stacktrace here already but it might be a bug in my code as well. It happens randomly whenever doing a lot of calls.... unsure if it's my code, dapr or python core code...

```bash
== APP ==   File "/home/xanrin/dapr-python-sdk/dapr/actor/client/proxy.py", line 71, in __call__
== APP ==     return self._message_serializer.deserialize(rtnval, self._attr_call_type['return_types'])
== APP ==   File "/home/xanrin/dapr-python-sdk/dapr/serializers/json.py", line 49, in deserialize
== APP ==     obj = json.loads(data, cls=DaprJSONDecoder)
== APP ==   File "/usr/lib/python3.7/json/__init__.py", line 361, in loads
== APP ==     return cls(**kw).decode(s)
== APP ==   File "/usr/lib/python3.7/json/decoder.py", line 340, in decode
== APP ==     raise JSONDecodeError("Extra data", s, end)
== APP == json.decoder.JSONDecodeError: Extra data: line 1 column 95 (char 94)
```
