### ISSUE TITLE
Add scenario based application examples

### ISSUE THREAD

**Issue by youngbupark** [dapr/python-sdk#85]
## Describe the proposal

Add more realistic application examples which can show the capabilities of the convenient layer.

**Comment by wmeints** [comment]
Hi @youngbupark we've built a nice workshop at Info Support that demonstrates how to use Dapr in a more realistic scenario: [edwinvw/dapr-workshop](https://github.com/edwinvw/dapr-workshop). I've created [the python version]( https://github.com/wmeints/dapr-workshop-python) for that workshop.  I think it could be a great source for people to learn how to use Dapr in Python.
