### ISSUE TITLE
Implement Dapr http callback to fastapi extension

### ISSUE THREAD

**Issue by youngbupark** [dapr/python-sdk#87]
## Describe the proposal

This is to implement the similar attributes in [asp.net integration](https://github.com/dapr/dotnet-sdk/tree/master/src/Dapr.AspNetCore) for http appcallback as a flask extension.

**Comment by wmeints** [comment]
Hi @youngbupark I'm not entirely sure what you have in mind here. Are you thinking along these lines?

** Topic bindings**
```python
@dapr.ext.fastapi.topic(app, "some-pubsub", "some-topic")
def my_handler(event_data):
  pass
```

**Comment by wmeints** [comment]
@berndverst I think this can be closed since the callbacks are now in the SDK.
