### ISSUE TITLE
Support default json serializer in DaprClient and add .json helper

### ISSUE THREAD

**Issue by youngbupark** [dapr/python-sdk#88]
## Describe the proposal

In [the convenient layer spec](https://github.com/dapr/python-sdk/issues/67), DaprClient doesn't have the default json serializer, but let users to handle JSON serialization. Like the other python pkgs, such as flask, requests, etc, DaprClient can have default json serializer to serialize and deserialize python dict type or primitive objects and provide .json() helper to DaprResponse and DataContent in AppCallback Layer. It will improve development experience instead of serializing and deserializing data object.

**Comment by chinzhiweiblank** [comment]
Will this work?
```
response = DaprResponse()
response.json() # Returns json
response.serialize() # Returns object
```

**Comment by chinzhiweiblank** [comment]
> Will this work?
> 
> ```
> response = DaprResponse()
> response.json() # Returns json
> response.serialize() # Returns object
> ```

Hey @youngbupark , I want to tackle this again. Could I ask if this is the result you seek?

**Comment by wcs1only** [comment]
Yes, I think your proposal matches what we're looking for here. Would be glad to accept a PR with these changes.
